Mobile version
sjdev2212/Capstone-1 pull request #1
Opened 2021-10-14 04:58 UTC by sj1978

In this project I :  
.Created HTML CSS and Javascript files, a read-me file, and linter folders .
.Created a mobile version of the home page and about page.
.Created a hamburger button for the navbar using javascript.
.Created a desktop version of the home and about page.
Created anchors in navbar to link them to the different sections of the page. 
.Created a featured speakers section dynamically using javascript for both mobile and desktop.
Checked for linter errors.

2021-10-14 06:42 UTC, rukundoeric requested changes
Hi @sj1978, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯

## Required Changes ♻️
  - [ ] You did not make a video presentation. Kindly make one and make sure to contain the following:
         -  a clear and objective description about the project in professional English. The topic and purpose of the project are made clear.
         - a demo of the project, showing the pages in different screen sizes.
         - a highlight about a piece of the code the you find interesting or you are proud of making.
  - [x] Home and About pages  must have different content. Kindly create about page and make sure that it has content similar to the one in the mockup design.
  - [ ] You app does not look like the mockup design. not even close. Kindly try to make sure that your app is at least almost identical to the mockup design in order to comply with the project specifications.
  
      | Original      | Yours |
      | ----------- | ----------- |
      | ![scrnli_10_14_2021_7-25-18 AM](https://user-images.githubusercontent.com/45217364/137263660-4357b60c-85c9-4ef2-bb36-aae04ea52291.png) | ![scrnli_10_14_2021_8-18-23 AM](https://user-images.githubusercontent.com/45217364/137263721-bea099fe-0e16-4016-b9fc-56d5ba8510f6.png) |
      | ![scrnli_10_14_2021_8-33-54 AM](https://user-images.githubusercontent.com/45217364/137264252-0c0f0e5d-0457-492c-9126-db7a2aa40b12.png) | ![scrnli_10_14_2021_8-31-58 AM](https://user-images.githubusercontent.com/45217364/137264292-a41e37a3-80b6-4e0e-a079-fe94a284ea14.png) |
       | ![scrnli_10_14_2021_8-36-46 AM](https://user-images.githubusercontent.com/45217364/137264666-913a06da-125b-4629-be86-649ede535007.png) | ![scrnli_10_14_2021_8-37-18 AM](https://user-images.githubusercontent.com/45217364/137264730-b7351c1e-16db-490b-8eb2-2bdb300725a4.png) |
       -  Colors, Fonts, Layouts orientation and spacing must be exactly the same.
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-14 06:42 UTC, rukundoeric commented on index.html
> +          <li class="nav-item"> <a href="#link-6">Past Events</a> </li>
- [x] <b>REQUIRED:</b> The app must contain at least two pages `Home and About`. that way it would be possible to navigate between them. but your links are not navigating anywhere. kindly fix it.

2021-10-14 06:42 UTC, rukundoeric commented on index.js
> +function toggleMenu() {
- [ ] <b>REQUIRED:<b/> Prefer using ES6 arrow function. Actually, there is nothing wrong with ES5 functions syntax but it is mandatory to use es6 features in the javascript module. besides, Arrow functions provide a simplified structure, allowing for a more concise way to write function expressions. which makes them better than ES5 functions(function declarations). Here is the syntax of an ES6 arrow function...
```javascript
  const functionName = () => {
     // code here
  }
```

2021-10-15 07:11 UTC, Davidosky007 requested changes
## Hi @sj1978 👋, 

Great work on making the changes requested by a previous reviewer 👏 
* Nice video presentation 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
* As the previous reviewer pointed out your design still looks different from the original design please note ✍️ that only the design, fonts, margin, colour etc should be followed but the contents can be personalized 
* Kindly compare highlighted areas below with the original design and make the necessary changes 🙏 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-15 07:11 UTC, Davidosky007 commented on about.html
> +  <header>
* KIndly add the top dark bar as it is in the original design 
![image](https://user-images.githubusercontent.com/52497246/137443133-eedd4e6d-794b-4bc6-80a4-f097f46ba5a9.png)

2021-10-15 07:11 UTC, Davidosky007 commented on about.html
> +        <ul class="nav-list">
* I suggest you make the navbar section align centrally as it is in the original design kindly compare with yours and make the necessary changes 
![image](https://user-images.githubusercontent.com/52497246/137443319-13fa343d-5fdc-4ed0-82df-0a477891ad9f.png)

2021-10-15 07:11 UTC, Davidosky007 commented on index.html
> +  </div>
* Kindly fix the footer section of all pages as it looks different from the original design 
* ORIGINAL 
![image](https://user-images.githubusercontent.com/52497246/137445902-294bbf8c-baf4-4d6b-9bb9-645d029c36b8.png)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------* YOURS 
![image](https://user-images.githubusercontent.com/52497246/137445963-c6110d8c-1941-4036-8fab-8dc199bf3714.png)

2021-10-15 16:30 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Anibal Amoroso, 
 ### Thank you for working on changes suggested previously :ok_hand:

## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-15 16:30 UTC, SajjadAhmad14 commented on about.html
> +    <footer class="footer-desk">
The footer should have a white background on mobile view. The content should be centered vertically and have the same margin from the right and left. KIndly follow the font guidelines from the design.
![footer](https://user-images.githubusercontent.com/35504149/137521776-48df62bf-b3be-48f7-82c3-e028cf77a53a.png)

2021-10-15 16:30 UTC, SajjadAhmad14 commented on .gitignore
> +node_modules
[ OPTIONAL ] Please add all unnecessary files and folders like `.vscode` to `.gitignore`.

2021-10-15 16:30 UTC, SajjadAhmad14 commented on about.html
> +      <nav class="container dark-nav">
[ OPTIONAL ] Social icons on the top nav bar should have the same design and font color from the design.
![socials](https://user-images.githubusercontent.com/35504149/137521818-dcf19fd5-b913-4946-bf77-f38bc06cc73c.png)

2021-10-15 17:47 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Anibal Amoroso, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-15 17:53 UTC, merged